/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pl.edu.agh.sr.middleware.thrift;


public enum TAccountType implements org.apache.thrift.TEnum {
  STANDARD(0),
  PREMIUM(1);

  private final int value;

  private TAccountType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TAccountType findByValue(int value) { 
    switch (value) {
      case 0:
        return STANDARD;
      case 1:
        return PREMIUM;
      default:
        return null;
    }
  }
}
