/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pl.edu.agh.sr.middleware.thrift;


public enum TCurrencyCode implements org.apache.thrift.TEnum {
  USD(0),
  EUR(1),
  CHF(2),
  GBP(3),
  PLN(4),
  SEK(5),
  RUB(6);

  private final int value;

  private TCurrencyCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TCurrencyCode findByValue(int value) { 
    switch (value) {
      case 0:
        return USD;
      case 1:
        return EUR;
      case 2:
        return CHF;
      case 3:
        return GBP;
      case 4:
        return PLN;
      case 5:
        return SEK;
      case 6:
        return RUB;
      default:
        return null;
    }
  }
}
