// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyservice.pl.edu.agh.sr.middleware.proto

package pl.edu.agh.sr.middleware.proto;

public final class CurrencyServiceProto {
  private CurrencyServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Currency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Currency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025currencyservice.pl.edu.agh.sr.middleware.proto\"U\n\010Currency\022\034\n\005c" +
      "ode1\030\001 \001(\0162\r.CurrencyCode\022\034\n\005code2\030\002 \001(\016" +
      "2\r.CurrencyCode\022\r\n\005value\030\003 \001(\001\"M\n\017Curren" +
      "cyRequest\022\034\n\005code1\030\001 \001(\0162\r.CurrencyCode\022" +
      "\034\n\005code2\030\002 \001(\0162\r.CurrencyCode*M\n\014Currenc" +
      "yCode\022\007\n\003USD\020\000\022\007\n\003EUR\020\001\022\007\n\003CHF\020\002\022\007\n\003GBP\020" +
      "\003\022\007\n\003PLN\020\004\022\007\n\003SEK\020\005\022\007\n\003RUB\020\0062B\n\017Currency" +
      "Service\022/\n\014CurrencyChat\022\020.CurrencyReques" +
      "t\032\t.Currency\"\0000\001B8\n\036pl.edu.agh.sr.middle" +
      "ware.protoB\024CurrencyServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Currency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Currency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Currency_descriptor,
        new java.lang.String[] { "Code1", "Code2", "Value", });
    internal_static_CurrencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CurrencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyRequest_descriptor,
        new java.lang.String[] { "Code1", "Code2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
