// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyservice.pl.edu.agh.sr.middleware.proto

package pl.edu.agh.sr.middleware.proto;

public interface CurrencyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrencyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CurrencyCode code1 = 1;</code>
   */
  int getCode1Value();
  /**
   * <code>.CurrencyCode code1 = 1;</code>
   */
  pl.edu.agh.sr.middleware.proto.CurrencyCode getCode1();

  /**
   * <code>.CurrencyCode code2 = 2;</code>
   */
  int getCode2Value();
  /**
   * <code>.CurrencyCode code2 = 2;</code>
   */
  pl.edu.agh.sr.middleware.proto.CurrencyCode getCode2();
}
